### ISSUE TITLE
RSS, Google News palaikymas naujienoms

### ISSUE THREAD

**Issue by justinaskav** [vu-sa/vusa.lt#22]
Šiuo metu nėra jokio RSS patrauklaus output'o, svarbu tą turėti tokiam naujienų puslapyje.

**Comment by justinaskav** [comment]
Google News palaikymas atliekamas atskirai, per Google Publisher Center.

**Comment by mrghosti3** [comment]
O kaip dėl RSS?

**Comment by justinaskav** [comment]
RSS yra tik formatas. Atom formatas yra naujesnis negu RSS ir jį palaiko visi modernūs feedai. https://somedudesays.com/2021/09/what-is-rss-and-atom/


Nėra reikalo abiejų palaikyti ir egzistuoja Laravel paketas, kuris leidžia palaikyti Atom, tai jį instaliavau, konfigūravau ir šiuo atveju tikrai užteks.
