### ISSUE TITLE
Instrukcijos, kaip naudoti `apache2` vietoj `php artisan serve`

### ISSUE THREAD

**Issue by justinaskav** [vu-sa/vusa.lt#27]
Kadangi PHP _built-in_ serveris galimai nepalaiko kai kurių įprastų funkcijų, tarkim [`<video loop></video>`](https://stackoverflow.com/questions/8088364/html5-video-will-not-loop), todėl reikėtų turėti galimybę įsidiegti po, pvz., apache2 serveriu.

Be to, bus artimesnė aplinka VU SA serveriui (taip pat reiktų apie _dockerį_ pagalvot irgi...)

- [ ] Kaip iki galo įsidiegti `apache2` (`libapache2-mod-php`)
- [ ] Kaip naudoti MariaDB (`mysql` principo duombazę vietoje sqlite)
- [ ] Kaip įsidiegti phpmyAdmin

**Comment by justinaskav** [comment]
Išplėsti šias instrukcijas:

- [ ] Kaip iki galo įsidiegti `apache2` (`libapache2-mod-php`)
- [ ] Kaip naudoti MariaDB (`mysql` principo duombazę vietoje sqlite)
- [ ] Kaip įsidiegti phpmyAdmin

**Comment by mrghosti3** [comment]
Ko trūksta, kad ši issue būtų realizuotas?

**Comment by mrghosti3** [comment]
Jeigu taip, tai realiai, geriausia čia būtų turėti atskirą markdown file, kaip `SETUP.md` . Bet pasidarysiu fork ir eksperimentuosiu, kaip gali atrodyti šitam instrukcijos.
