### ISSUE TITLE
Atnaujinimo į production optimizavimas

### ISSUE THREAD

**Issue by justinaskav** [vu-sa/vusa.lt#46]
Reikia su CI sudirbt, pasidomėti Github Actions'ais ir susitvarkyti.

**Comment by mrghosti3** [comment]
Prabėgom peržiūrėjau, bet gal naudinga info ties pricing ant Github Actions.

Sutrumpintas proceso apibūdinimas:
- Npm build su kuriuo kompiliuojamas VueJs ir visa kita.
- Zip archiving prod files (php, frontend dalis) ir išsaugotu juo kaip release paketą.
- Tureti shell script arba webhook kuris parsiųstų naujausią release.

**Comment by justinaskav** [comment]
Padaryta be release'ų sistemos su #289
