### ISSUE TITLE
Naudoti useRemember formose

### ISSUE THREAD

**Issue by justinaskav** [vu-sa/vusa.lt#60]
Kad atsimintų jau įvestas reikšmes formos, pakeitus puslapį. Naudinga Inertia funkcija.

**Comment by mrghosti3** [comment]
O tokio dalyko neatlieka jau naršyklė?

**Comment by justinaskav** [comment]
Nesu labai įsigilinęs, bet spėju Inertia kiek kitaip veikia. Štai čia daugiau informacijos: https://inertiajs.com/remembering-state

Nėra labai sunkus dalykas, buvau ant vienos formos išbandęs, tai veikia.

**Comment by mrghosti3** [comment]
Ai, nu čia, kiek pagavau, cachina website. Bet reiktu pasidomėti ir naršykle, gal jos koki panašu funkcionaluma vygdo, nes tikrai ten gali fillint forma su dažnai pildomais duomenimis. Tik tam galbut reiktu labels ar ka prideti.
