### ISSUE TITLE
Sukurti aprašomąjį wiki, sumažinti README.md

### ISSUE THREAD

**Issue by justinaskav** [vu-sa/vusa.lt#89]
Kaip minima #83

**Comment by mrghosti3** [comment]
> Rašau, kad labiau susisteminti šita darbą.

- [ ] Atnaujinti svetainės diegimo intrukcijas
- [ ] Palengvinti README navigavimą
- [ ] Įterpti turinį į README

**Comment by mrghosti3** [comment]
Atsižvelgiant į tai, kyla klausimas dėl `php8.0-sqlite3` reikalingumo. Jis po kol kas nurodytas kaip `Prerequisite`, bet kadangi yra labiau rekomenduojama mysql server diegti, tai manau visai saugu išimti jį iš reikalavimų sąrašo. Kaip tu manai?

**Comment by mrghosti3** [comment]
Ar dar apsimoka naudoti `php artisan serve` ar vis dar labiau patartina naudoti Apache su MySQL?

**Comment by justinaskav** [comment]
Developmentui tai tikrai tokia tvarka

1. Laravel Sail (Docker)
2. `php artisan serve`
3. Apache MySQL

**Comment by mrghosti3** [comment]
https://github.com/mrghosti3/vusa.lt/blob/89-README-update/SETUP.md

Naujausias pakeitimas ant `SETUP.md`. Drąsiai rašyk komentarus čia, jeigu kas ne taip.

**Comment by justinaskav** [comment]
Būtų patogiau, jeigu jau sukurtum pull requestą ir tada tiesiogiai galėčiau eilutes pakomentuoti

**Comment by mrghosti3** [comment]
Oh yeah, pamiršau kad taip geriau daryt. Sorry, seniai labai PR naudojau. Ryt iš ryto pakursiu.
