### ISSUE TITLE
Migration error in 2022_06_14_130000_seed_with_records.php

### ISSUE THREAD

**Issue by mrghosti3** [vu-sa/vusa.lt#96]
**Klaidos aprašymas**
Meta klaidą vygdant `php artisan migrate:fresh --seed` 

**Kaip atkartoti klaidą**
Žingsniai klaidos atkartojimui:
1. freshly clone the project.
2. run `php artisan migrate:fresh --seed`

**Asmeninis kompiuteris (užpildykite šią informaciją):**
 - OS: Ubuntu 22.04

**Log**
```
In 2022_06_14_130000_seed_with_records.php line 18:
   file_get_contents(database/vusa_www-2022.sql): Failed to open stream: No such file or directory
```

**Comment by mrghosti3** [comment]
Būtų gerai patikslinimas, kam šitas yra skirtas:
https://github.com/vu-sa/vusa.lt/blob/3715df13da44506a70de0bd0d89ee57bee0f264b/database/migrations/2022_06_14_130000_seed_with_records.php#L17-L19

Nes tokius panašius atvejus būtų gerai paminėti `SETUP.md` #89

**Comment by justinaskav** [comment]
Tai yra paminėta README.md

<img width="764" alt="image" src="https://user-images.githubusercontent.com/23059846/183246103-37dae2bf-3494-4bc6-a91c-9cede426527c.png">

Čia yra SQL failas su duombazės įrašais testavimui.

**Comment by mrghosti3** [comment]
Oof. Reikėjo būti atitesniam tada. Nu pridesiu prie zinutes papildoma info ir paryskinsiu is savo puses.

**Comment by mrghosti3** [comment]
Sorry, kad ilgai dingau be jokiu atnaujinimų. Sakyk, kokios galimos reikšmės ant `app.env`? `prod`, `dev` ir `local`?

**Comment by justinaskav** [comment]
Viskas gerai :D Šiaip "local" ir "production" yra naudojamos Laravel reikšmės, jeigu neklystu.

**Comment by mrghosti3** [comment]
Gali būti. Dar po kol reikėtu pasiskaityt man Laravel docs.

 Mane tiesiog domina ar galima būtų padaryti, jog šita migracija kažkaip skip. Nebent jinai kažkokius svarbius duomenis sukelia/paruošia, tada gal reikėtu padiskutuoti ar būtų galima kažka pakeisti.

**Comment by justinaskav** [comment]
Jo, aš suprantu.

Tiesiog čia man reikia imti ir sutvarkyti, kad būtų užseedinama duombazė be klaidų.

Tai kitu darbu ir prisėsiu prie šito.

**Comment by mrghosti3** [comment]
Jeigu kas galėčiau gal kiek kartu prisidėti.

Kitu atveju, tada keep me up to date per šitą issue :D
